spring.application.name=TennisCenter
spring.datasource.url=jdbc:postgresql://localhost:5433/tennis_db
spring.datasource.username=postgres
spring.datasource.password=Simonahalep2003!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.upload.dir=uploads

server.port=8080

jwt.secret=1234567890123456789012345678901234567890123456789012345678901234
jwt.expiration=86400000
